### ISSUE TITLE
Programs are not executed in Firefox

### ISSUE THREAD

**Issue by kkeri** [wipplelang/wipple#113]
I tried the Wipple playground in Firefox 113 on Ubuntu 22.04. The programs in code boxes don't run and I get the following error message in the console window, apparently for each code block.

SyntaxError: export declarations may only appear at top level of a module
at worker-1e0324df.js:18:21590

In Chrome and Chromium however they run properly.

**Comment by WilsonGramer** [comment]
I just tested in Firefox 114 and everything appears to be working, so please update your browser and let me know if it works for you! The issue was that Firefox didn't support ES Modules in Web Workers, but they added support in version 114: https://www.mozilla.org/en-US/firefox/114.0/releasenotes/#note-789543
